### ISSUE TITLE
Touch input not behaving as expected

### ISSUE THREAD

**Issue by gingerbeardman** [JohnEarnest/Decker#1]
Hi!

Firstly, this is amazing! Well done. 

**Problem**
I've been trying the Tour on my iPhone and taps on elements like a checkbox or a button don't behave as expected. 

Unfortunately this means I can get stuck and have to reload/refresh the page. 

**What I'm seeing**
- one tap turns checkbox both on and off

**What I'm expecting**
- first tap to toggle on
- second tap to toggle off

**Screen recording**

- checkbox can't be toggled on
https://user-images.githubusercontent.com/49612/198755817-7011a5f3-cafa-41c9-822f-f0fa28aa8d95.MOV

- dialog can't be dismissed
https://user-images.githubusercontent.com/49612/198756007-cda0a4e8-ca6f-496b-95d4-81b13a91fc1e.MOV

**My setup**
- iPhone SE 2020
- iOS 16.1
- mobile Safari

**Comment by JohnEarnest** [comment]
Good catch. I can reproduce the same misbehavior in Chrome on a Windows-based tablet. I'll investigate.

**Comment by JohnEarnest** [comment]
I think I understand the source of the problem, and I have a patch that works on Windows. Flush your caches, re-fetch the tour at https://beyondloom.com/decker/tour.html and let me know if that fixes it on iOS.

**Comment by gingerbeardman** [comment]
It's fixed!

Thank you
