### ISSUE TITLE
Font documentation inconsistency

### ISSUE THREAD

**Issue by olus2000** [JohnEarnest/Decker#11]
The documentation of [font records](https://beyondloom.com/decker/format.html) states:

> Decker fonts define glyphs corresponding to printable ASCII excluding the space character (33–126; 95 glyphs total), an extra glyph representing an ellipsis (for truncating text on display), (...)

There is an error in this text alone, since there are 94 characters between 33 and 126, which make 95 characters when the ellipsis is included. However the actual font data present in the source code contains 96 glyphs, including the space glyph as the first one. This causes redundancy: there's the header byte defining the number of horizontal pixels to advance for a space character, and there's a glyph record for the space character with its own specified width.

I have not yet looked at how it's handled in code, but only one of those space width declarations should stay in the format, as it may lead to inconsistencies when they differ. My preference would be towards allowing full space glyph customization.

**Comment by JohnEarnest** [comment]
@olus2000 please refer to my recent commit, which I believe addresses both of your concerns.

**Comment by olus2000** [comment]
Ah, I didn't notice it. I believe that indeed addresses my issues.
