### ISSUE TITLE
Widget Bounds disappear after 'Fat Bits' is enabled and disabled

### ISSUE THREAD

**Issue by razetime** [JohnEarnest/Decker#14]
Problem is present in both JS and C versions.

**Reproduction:**
- Menu: `Tool → Widgets`
- Menu: `View → Fat Bits` (do it twice)
Bounds should not be visible, and `View → Show Widget Bounds` leaves it the same (no bounds).

**Comment by gingerbeardman** [comment]
I think the problem here is activating Fat Bits automatically changes to the Pencil tool.

So, you'll need to do Tool > Widgets again to see the bounds.

**Comment by JohnEarnest** [comment]
Just for references, @gingerbeardman is correct; FatBits is for drawing, not editing widgets, so if you aren't using a drawing tool, enabling FatBits switches to one automatically. It's meant as a convenience, but I'll note the confusion.
