### ISSUE TITLE
Addition of strings produces 0

### ISSUE THREAD

**Issue by olus2000** [JohnEarnest/Decker#16]
### Bug report
According to Appendix 2 to Lil documentation: Binary Primitives operator `+` when acting on two strings should concatenate them:

> Note that using `,` on two strings will result in a list of two strings, whereas using `+` will result in a single string!

### How to reproduce
Open the Listener and run query `"a" + "b"`.

### Expected outcome
Listener returns the string "ab".

### Actual outcome
Listener returns the number 0.

**Comment by JohnEarnest** [comment]
Resolved by #17
