### ISSUE TITLE
`x` in query expressions is bount to the table

### ISSUE THREAD

**Issue by olus2000** [JohnEarnest/Decker#18]
### Bug report
Query expressions exhibit undocumented behavior, binding the table being queried to the variable `x` which shadows

### How to reproduce
Run the following code in the Listener:
```lil
test_table: insert a:"x","y" b:1,2 into 0
extract x from test_table
```

### Expected result
The default value for unbound variables - 0.

### Actual result
A table equivalent to `test_table`.

**Comment by JohnEarnest** [comment]
I believe this has been resolved; feel free to reopen if there's a problem.
