### ISSUE TITLE
Widget names with spaces make Lil references not work?

### ISSUE THREAD

**Issue by gcanyon** [JohnEarnest/Decker#19]
If I have a field named: wanda fish
and code in a button like so:

on click do
 wanda fish.text:wanda fish.text*2
end

The code will not work. I've looked through the docs for any reference to this, and tried single and double quotes, square and curly braces, and parentheses, to no avail.

**Comment by JohnEarnest** [comment]
If you use spaces (or other non-identifier characters) in a widget name, it won't be available as a "magic" lil variable. You can still access it via the card's `widget` attribute, which is a dictionary keyed by strings:

```
on click do
  card.widgets["wanda fish"].text:card.widgets["wanda fish"].text*2
end
```

The same is true for card names containing special characters, which can be accessed via `deck.cards["special name"]`.

**Comment by gcanyon** [comment]
Ah, great. Okay if I do a pull request on the docs? I'd love to add this and any other notes I come up with.

**Comment by gcanyon** [comment]
Ha -- I was going to ask what happens if I give two controls the same name, but I see Decker won't allow that :-)
