### ISSUE TITLE
Upscaled canvas is blurry in some situations

### ISSUE THREAD

**Issue by gingerbeardman** [JohnEarnest/Decker#2]
**Problem**

This is more noticeable on my MBP with retina screen, but is perhaps an issue a cross the board.

The canvas seems to be upscaled with bilinear(?) filtering on, even though the dimensions are kept to integer scale.

The results are a slightly blurry image, in shades of grey rather than pure black and white.

## Where

- web app
- macOS app
  - windowed
  - fullscreen

## Screen grabs

Here are some zoomed screen grabs.

**What I see**
![decker-scaling](https://user-images.githubusercontent.com/49612/198823841-b95a4d20-f3d1-4a2d-8345-888f3f9c6554.png)

**What I expect**
![decker-scaling-expect](https://user-images.githubusercontent.com/49612/198823840-c49da1fa-a6b2-45f3-b30d-c8a0dcef307d.png)

**Comment by JohnEarnest** [comment]
Experimenting with a few browsers, it looks like
```
canvas{image-rendering:pixelated;}
```
achieves the desired effect, and compatibility matrices suggest it should be portable.

I also enabled `SDL_WINDOW_ALLOW_HIGHDPI` for native builds.

**Comment by gingerbeardman** [comment]
Even with that CSS I'm still seeing the issue on the web version.

Curious.

**Comment by JohnEarnest** [comment]
You could try `image-rendering: crisp-edges` instead, and make sure you don't have some sort of zoom override in effect. I'm already using `CanvasRenderingContext2D.imageSmoothingEnabled=false` on the JS side. Beyond vendor-specific flags there isn't much more within my control.

**Comment by gingerbeardman** [comment]
I'll keep proving this, but it seems like everything is being drawn on a half pixel boundary if that makes sense? I'll check on a non-retina display tomorrow.

**Comment by JohnEarnest** [comment]
Hmm. Is it possible that your display/window size is resulting in the canvas itself being positioned at a pixel boundary?

**Comment by gingerbeardman** [comment]
I don't know, I'm using standard/default scaling and have tried all others, but I'll endeavour to find out for sure!

**Comment by gingerbeardman** [comment]
Well, look at that. 

It's blurry in Safari but fine in Chrome!

**Blurry**
- Safari 16 (macOS & iOS)
- Safari Tech Preview (macOS)

**Sharp**
- Duck Duck Go (WebKit)
- Chrome
- Brave (Chromium)

So suffice to say it seems to be a Safari issue and I'll be happy to report it there if/when we agree it makes sense.

My only reservation: canvas tools of my own, eg https://www.gingerbeardman.com/pangds/ do not suffer from this issue.

**Comment by JohnEarnest** [comment]
Well, that certainly helps narrow things down. For what it's worth, I've done most of my testing and development on Safari 14 and 15, and I do not observe the issue, which suggests the problem is either a recent regression in Safari or some other detail of your environment.

**Comment by gingerbeardman** [comment]
Indeed! I'm trying to find some old versions of Safari Tech Preview to try to bisect.

**Comment by gingerbeardman** [comment]
Hmm. Decker Mac app suffers from this, which makes no sense to me as it's powered by SDL2 rather than WebKit, right?

**Comment by JohnEarnest** [comment]
The mac app apparently requires [an additional plist setting](https://wiki.libsdl.org/SDL_WindowFlags#remarks) to take advantage of high DPI displays. I will ensure that this is included in the next native release.

**Comment by gingerbeardman** [comment]
This really is the most strange thing.

**Comment by JohnEarnest** [comment]
As of the latest binary release (v1.1) I've applied all of the mitigations I'm aware of for this issue and can no longer reproduce any misbehavior on my machines, so I don't see any further action to take here.

If anyone has a specific, actionable suggestion for improving pixel accuracy feel free to reopen in the future.

**Comment by gingerbeardman** [comment]
Hurrah! Many thanks.

Just to report back the current state:

## macOS app
- nice and sharp!

## web app
- still blurry on some browsers (see [list above](https://github.com/JohnEarnest/Decker/issues/2#issuecomment-1297728642))

So there are solutions for both.
