### ISSUE TITLE
[Question] How to create links in rich text ? 

### ISSUE THREAD

**Issue by indrajithk** [JohnEarnest/Decker#21]
The documentation says 

"Rich text hyperlinks are only “clickable” when their field is locked. With scripting, a link can do anything a button can do when it’s clicked, but by default if you use the name of a card as the link value, clicking the link will navigate to that card. If you use a URL, clicking the link will have Decker prompt you to open the URL in a web browser."

I tried different means to create a hyperlink, none of them succeeded. Probably I misunderstood the docs. Can you clarify how to go about creating  the things mentioned in the docs (doc:"Rich Text fields can contain multiple fonts, inline images, and clickable hyperlinks."). 

Or is it that these can only created by scripting?

**Comment by JohnEarnest** [comment]
If you create a rich text field, switch to the "Interact" tool, and then click in the field, you will be given a "Text" menu. If you make a selection, you can use items in this menu to change the font and/or insert a link in that selection. If you want to link to a URL, remember to include the `http://` or `https://` prefix when creating the link.

Also, if you're using web-decker, I just identified and fixed a regression in the link dialogue, so be sure to clear your browser cache.
