### ISSUE TITLE
[Question] How to add new font ?

### ISSUE THREAD

**Issue by indrajithk** [JohnEarnest/Decker#23]
By default Decker comes with three fonts. It seems new fonts needs to be added from other decks containing (there is an example deck available in the distribution) using File -> Resources. 

a. Is there a way to add system fonts easily inside Decker ? What is the preferred way ?
b. For every font size is it required to add a new font?

**Comment by JohnEarnest** [comment]
a) There is no way to directly import system fonts into Decker; Decker has its own format for bitmapped fonts. See the discussion in [this forum post](https://itch.io/t/2455731/importing-custom-fonts-from-file) for details.

b) Every decker font consists of a collection of glyphs with one size.
