### ISSUE TITLE
Sound recording - quality is poor

### ISSUE THREAD

**Issue by indrajithk** [JohnEarnest/Decker#24]
The default way to record new sound leads to poor quality. 

a. Is there a way to improve the sound quality of spoken voice? 
b. Is there a way to import wav files from the disk?

**Comment by JohnEarnest** [comment]
Decker audio is stored and recorded as 8khz monophonic audio, which imposes limits on the achievable recording quality.

Decker records audio using the default input device provided by your device. Quality will vary from device to device. Your operating system may provide gain settings or other configuration options over which I have no control.

WAV files may be imported into Decker by dragging and dropping them into the window, manually imported from disk (File -> Sounds... -> New... -> Import Sound...), or imported procedurally from scripts using the `read[]` function.

**Comment by indrajithk** [comment]
OK; Looks like the recording should done bit louder. Closing it, as it resolves under the given constraints. Thank you.
