### ISSUE TITLE
Toggle fat bits mode

### ISSUE THREAD

**Issue by gingerbeardman** [JohnEarnest/Decker#26]
Currently fat bits mode can be entered using a modifier key plus click.

It would be very useful for the selection to be able to get out of fat bits mode with the same technique.

HyperCard achieved this by use of a modifier key when using the Pencil tool to toggle the mode on/off with repeated invocations.

From #3

**Comment by JohnEarnest** [comment]
I'm not really sure what the benefit is to this over the current method of exiting FatBits via the keyboard- pressing escape. Can you clarify?

**Comment by gingerbeardman** [comment]
Coming from HyperCard (as I'm assuming a high percentage of users will be) it's usual to keep your finger on the modifier keys and use presses of the command key to zoom in and out whilst drawing pixel graphics.

So it's both quicker to only have to use the one key to enter and exit fat bits, and it is familiar for HyperCard users (I didn't realise you could exit it using escape, I just assumed that you had to use the menu).

**Comment by JohnEarnest** [comment]
The above commit completes the requested addition.

**Comment by gingerbeardman** [comment]
Many thanks, John.
