### ISSUE TITLE
Draw with pattern using modifier key

### ISSUE THREAD

**Issue by gingerbeardman** [JohnEarnest/Decker#28]
It would be useful to be able to draw with a pattern quickly without having to use the menu.

Using a modifier toggle would be quick and easy.

HyperCard achieved this by use of a modifier key when using the following tools:

- Pencil
- Line
- Shapes

The goal here is to make for a more optimised, quicker, frictionless drawing experience.

From #3

**Comment by JohnEarnest** [comment]
Decker presently allows the user to choose a foreground and background pattern for any drawing tool via the palette modals under `Style -> Stroke` and `Style -> Fill`, or, when enabled, the right toolbar. Decker treats patterns as "logical colors", and retains them when copying, pasting, moving selections and performing fills.

I'm unclear on what is being asked for here distinct from the present behavior.

**Comment by gingerbeardman** [comment]
Thanks John, this issue was indeed not very clear!

I've edited it. But as you say Decker already allows this without use of a modifier.

In HyperCard the modifier I guess is a substitute for the (then absent) right mouse button.

Anyway, here is me drawing some lines with solid colour and the holding modifier to draw a patterned line in HyperCard.


https://user-images.githubusercontent.com/49612/200195849-89f44d01-c1f7-4af6-9aa2-2fe5a9b3ee7f.mov
