### ISSUE TITLE
HyperCard-like modifier keys

### ISSUE THREAD

**Issue by gingerbeardman** [JohnEarnest/Decker#3]
**Request**

HyperCard allowed using the modifier keys to trigger alternate drawing features and modes.

eg.
- Cmd + Lasso = selection will be tight to any enclosed pixels
- Cmd + Pencil = toggle flat bits mode
  - currently in Decker this sort-of works to enter fat bits mode, but not to exit it
- etc

It would be cool to see them all in Decker.

**Justification**

The best HyperCard artists made extensive use of them. For example, I've heard this first hand from Thoru Yamamoto: https://archive.org/details/thoru-yamamoto-hypercard-stacks (viewable in browser)

**HyperCard docs, see Chapter 8**
- https://cancel.fm/stuff/share/HyperCard_Reference_1.pdf

**Reference**

![image](https://user-images.githubusercontent.com/49612/198824510-cee7189e-7a65-4bad-8d7f-032eee774133.jpeg)

**Comment by JohnEarnest** [comment]
This is very open-ended, and should probably be broken down into specific feature requests with more detail on the desired behavior. Decker does not aim to slavishly replicate HyperCard's behavior. Some tools are missing or designed differently, and some of these features are actually already implemented or have an alternate method of access.

For example, Decker doesn't have a separate eraser tool, there's no curve tool, shift makes the line tool snap to 45 degree angles, shift makes the rectangle and oval tools snap to squares and circles respectively, and escape exits FatBits (for consistency with dismissing most other "modes" like the script editor).

It is also important to consider that, in general, browsers and operating systems impose some constraints on shortcuts which can be used, and mobile devices have none of these modifier keys.

**Comment by gingerbeardman** [comment]
I will break this one down, cheers!

**Comment by JohnEarnest** [comment]
I'm going to mark this issue as closed, because I don't think it's actionable in this form, but as I said previously I am entirely open to discussing the addition of _specific_ tools and/or shortcuts in their own issues.

**Comment by gingerbeardman** [comment]
Have split out the half dozen issues, as promised. Thanks!
