### ISSUE TITLE
Grids are blank after importing data from a CSV while a format is applied

### ISSUE THREAD

**Issue by ahribellah** [JohnEarnest/Decker#32]
So I set up a small application that returns random entries in a grid based on whether or not the user has checked a box next to each item in the grid and there are two things I've noticed that make working with grids a bit unfun.

The lists were long, so I used CSVs that I edited in Excel to populate the grids. That's not really a problem. I prefer that to building the list in the editor when one list is >100 items long.

The way I had it set up is that one column was a bool (technically 0 or 1) and the other was a string. I set the format to `BL`.

However, if I made changes to one of the CSVs and tried to reimport it, it would pull the column headers, but everything else would be blank.

I later discovered that I had to remove the format that I had set, reimport it, and then reapply the format to get the desired result.

I'm not sure if this applies to all formats or just the ones I chose, but it would definitely be nice to not have to mess with a grid's format just to reimport data.

**Comment by JohnEarnest** [comment]
Oof. That's a design oversight on my part. Apologies.

Importing CSVs uses column formats from a grid when they're available, so that data is stored using an appropriate datatype, but when I added the special column formats (`I`,`B`,`L`) which are grid-specific I did not update the CSV parser/formatter to interpret them properly.

**Comment by JohnEarnest** [comment]
Please give this patch a try; should be a bit less error-prone.

**Comment by ahribellah** [comment]
I would, but I'm not entirely sure how to build this on Windows. The makefile doesn't have a target for any of the usual Windows systems and I'm running up against a collision with `setmode()` in io.h when I try to modify it to work with MSYS2's MinGW64 terminal.

```
./c/decker.c: At top level:
./c/decker.c:265:6: error: conflicting types for 'setmode'; have 'void(int)'
  265 | void setmode(int mode){
      |      ^~~~~~~
In file included from D:/Applications/msys64/mingw64/include/sys/stat.h:14,
                 from ./c/dom.h:2241,
                 from ./c/decker.c:3:
D:/Applications/msys64/mingw64/include/io.h:342:15: note: previous declaration of 'setmode' with type 'int(int,  int)'
  342 |   int __cdecl setmode(int _FileHandle,int _Mode) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
```

**Comment by JohnEarnest** [comment]
I'm told that Decker builds successfully under WSL.

At any rate, these changes are reflected in the [latest public build (v1.1)](https://internet-janitor.itch.io/decker/devlog/447965/decker-11) and the live copy at https://beyondloom.com/decker/tour.html

**Comment by ahribellah** [comment]
> I'm told that Decker builds successfully under WSL.

Does it build as a *native* executable, though? Not a Linux executable? There's a pretty big difference. One requires you to run a Linux emulation *and* an X Server to run the application.

You're offering native Windows executables on itch.io, so you have some sort of process that is working to build native Windows executables. I'm just confused as to why it seems that I can't replicate that easily (and why the Makefile only has conditionals for Linux and Mac).

> At any rate, these changes are reflected in the [latest public build (v1.1)](https://internet-janitor.itch.io/decker/devlog/447965/decker-11) and the live copy at https://beyondloom.com/decker/tour.html

I loaded my deck in Decker 1.1 and reloaded the CSV and it did not immediately go blank, so it is fixed. Given that, I'll close the comment.

**Comment by indrajithk** [comment]
It would be nice to know how to build this on Windows. By default windows build is not a target in the Makefile. May be how you are producing the native distribution for Windows on itch.io would help.
