### ISSUE TITLE
Performance testing of Decker - Program degrades at around 5000 - 6000 cards and crashes at 10K cards

### ISSUE THREAD

**Issue by indrajithk** [JohnEarnest/Decker#33]
Test is mainly opening the deck and typing some characters in fields and saving. 

At around 1000 cards, the system is responsive. I am using Windows 10, 32GB RAM. The binary distribution is as downloaded from itch.io.

(Step 1) The opening time increased with the number of cards (for 6000 cards it was very noticeable running to few seconds). Step 2 is to check all the cards are opened via File -> Cards and then scrolling to the bottom and see if all the cards are opened. In all cases Decker imported all the cards.  Next (Step 3) involved doing some authoring by typing some characters into the fields and saving. Saving had a performance drop when the number of cards increased. When it had about 10,000 cards save didn't succeed. The program exited on save.  

Decks were generated using the python script below. Script below for reference. 

```
header = r'''{deck}
version:1
card:0
size:[512,342]
name:"perftest03.deck"'''

field_def = r'''{widgets}
field1:{"type":"field","size":[239,289],"pos":[37,35]}
field2:{"type":"field","size":[205,60],"pos":[298,34]}
field3:{"type":"field","size":[205,60],"pos":[298,107]}
field4:{"type":"field","size":[205,60],"pos":[298,185]}
field5:{"type":"field","size":[205,60],"pos":[296,262]}'''

def generate_deck_name(count):
    return "card"+str(count)

def generate_deck_header(count):
	card_first_line = "{card:"+generate_deck_name(count)+"}"
	return card_first_line
	
def generate_deck_body():
	global field_def
	return field_def

if __name__ == '__main__':
	deck_file = open("perftest03.deck",'w')
	deck_file.write(header)
	deck_file.write("\n")
	deck_file.write("\n")
	for i in range(1,6000):
		deck_name = generate_deck_name(i)
		deck_file.write(generate_deck_header(i))
		deck_file.write("\n")
		deck_file.write(generate_deck_body())
		deck_file.write("\n")
		deck_file.write("\n")
	deck_file.close()

```
The test was motivated by a video in which Bill Atkinson was talking about Hypercard being able to manage unlimited number of cards only limited by system constraints. The reasoning was that, Hypercard always read each card from disk and committed any unsaved things to the disk necessitating no explicit save. Decker deviates from this principle, though it is not bound to stick with original Hypercard ways. But, it is always good to have unlimited capacity esp a related system in the past had it as one of its main design consideration.

**Comment by JohnEarnest** [comment]
Decker serializes files in a text-based, human-readable, diff-friendly format, which is fundamentally at odds with the kind of bookkeeping that would be necessary for partial file writes and dynamically paging cards out of memory. Delivering documents as monolithic HTML files poses similar problems. Nonetheless, I consider each of these characteristics essential.

Some degree of lazy hydration is possible, and there are many small efficiencies in both performance and storage to be gained by improving the implementation, but supporting an "unlimited" number of cards does not seem like a reasonable design goal in light of other constraints and functionality.

In fact, it might be prudent to introduce arbitrary limits- say, 1024 cards and 256 widgets per card, perhaps- to help ensure that a valid document can always be consistently handled.

**Comment by indrajithk** [comment]
Closing this issue as there is no action here. As mentioned some limits might be help to make sure any valid documents can be handled.

**Comment by gingerbeardman** [comment]
FWIW whilst looking at the old animations I'm recreating, I've seen card counts approaching 1000.

**Comment by JohnEarnest** [comment]
I also did a little research into Myst and the closest figure for screens I can find is "about 2500".

**Comment by gingerbeardman** [comment]
Yes, I read that just now.

> "2500 rendered images, 40 minutes of original music,
> 66 minutes of Quicktime animation, 2 years in the making."

https://mystjourney.com/myst/making-of/
