### ISSUE TITLE
some monospace fonts

### ISSUE THREAD

**Issue by ktye** [JohnEarnest/Decker#34]
i generated some monospace fonts:

https://github.com/ktye/i/tree/master/_/i2/kui/f
files `*.dek`

generated with `mkdek`

the png files for the plan9 fonts seem to have issues.

**Comment by JohnEarnest** [comment]
Nice!

If you combined those ".dek" files into a minimal [decker file](https://beyondloom.com/decker/format.html) like
```
{deck}
version:1
{fonts}
first:"%%FNT0..."
second:"%%FNT0.."
```

They would be a bit easier for people to import.

It looks to me like they need a glyph for the ellipsis character, too.

**Comment by ktye** [comment]
here you go:
https://github.com/ktye/i/blob/master/_/i2/kui/f/fonts.deck

for the ellipsis, i just copied the dot.
i don't think 3 dots fit in the monospace.
would 2 dots be ok?

**Comment by JohnEarnest** [comment]
Sure, 2 dots is OK.

**Comment by 1jss** [comment]
@ktye Do you mind me adding these fonts to my [decker-fonts](https://github.com/1jss/decker-fonts) repo? You will of course be credited in the readme.

**Comment by ktye** [comment]
@1jss i don't mind. please go ahead. note that the ellipsis are still missing. maybe you can add them by copying dots in the font editor.

**Comment by JohnEarnest** [comment]
Thanks for providing these, @ktye. Since there really isn't anything else to do here, I'll mark this as closed.
