### ISSUE TITLE
copy/paste keyboard shortcuts not working in Decker web editor

### ISSUE THREAD

**Issue by traws0** [JohnEarnest/Decker#38]
open any text area in Decker web and select some text
shortcuts ^c/^v/^x do not work for the selected text.

**Comment by JohnEarnest** [comment]
In what browser/OS?

**Comment by traws0** [comment]
firefox/windows

**Comment by JohnEarnest** [comment]
From [the manual](https://github.com/JohnEarnest/Decker/blob/main/docs/decker.md#web-decker-and-native-decker), 

> Copying, cutting, and pasting from the keyboard _must_ be done using the native OS/Browser keyboard shortcuts. Copying and pasting using the menus may require you to confirm the action with a browser modal. When pasting via the keyboard, it may be possible to paste images and sounds from the OS clipboard. Clipboard access is very flaky and inconsistent between browsers: Web-Decker tries several strategies to interact with the OS clipboard, but if nothing works it will store clipboard contents in a local window-only clipboard instead, accessible via the browser console as the `local_clipboard` variable.

In my experience, Firefox has the worst/flakiest clipboard support of any browser I've tested. Command+C/V/X seem to work for Firefox in OSX.

- Can you copy and paste _within_ Decker, but not interact with the system clipboard?
- Does copying and pasting from menus work?
- Do you get anything suggesting an error in the JS console?
- Is `local_clipboard` set JS-side after a copy?
- Are you running any browser plugins which could potentially interfere with Decker?

**Comment by traws0** [comment]
ok, did some more testing. 
keyboard shortcuts also do not work in Chromium and Edge (no plugins).
using the menu to copy sets the local_clipboard variable
using the menu to paste shows the external clipboard after accepting the modal in Chromium/Edge (no modal in Firefox) 
no errors in JS console

**Comment by JohnEarnest** [comment]
This really threw me for a loop, but I think I tracked it down; In OSX `keyEvent.metaKey` is set for cut/copy/paste events, but on Windows it's `keyEvent.ctrlKey`. Naturally, the one place I forget this is the source of my woes.

**Comment by traws0** [comment]
yep, that fixed it. thanks.

**Comment by JohnEarnest** [comment]
Thanks for reporting. Given the severity of the problem I'm very surprised this wasn't found earlier.
