### ISSUE TITLE
Representation of big numbers in lil

### ISSUE THREAD

**Issue by traws0** [JohnEarnest/Decker#39]
Maybe I'm stretching too far the intended use of lil or it's just another windows-specific issue but in the native version (windows wsl):

`r:1 each x in 1+range 10 r:r*r*x end r`
returns

```
583617587388727090858100711201107859493172229546854534563669836 p ~      }K        Q      N      :~       N     ` |     r,      ` |     p ~       }        Q    ` |     p ~             R             "@        pE      ` |
```

In the web version within decker it returns the correct result in the format: `5.83..e+224`

I don't know if the intended behavior is diplaying all digits or using scientific notation.

Either way, another related question is the definition of `e`  as euler constant. It may trip people trying to input small or big numbers in scientific notation.

Example:
`1e-3`
returns
`-0.281718`

**Comment by JohnEarnest** [comment]
Well, I'd say both of those outputs are wrong to at least some degree. The native version clearly looks like some kind of nasty buffer overrun; will investigate.

Lil doesn't have scientific notation literals, though using them for `show[]` wouldn't be the first place where output is not prettyprinted in a manner that will round-trip.

**Comment by JohnEarnest** [comment]
The above patch corrects the immediate problem, though results are still printed inconsistently between implementations, since both interpreters still defer to their host language- `printf()` for native, and `Number.toString()` for JS.

**Comment by JohnEarnest** [comment]
The above patch resolves the inconsistency. If you have a huge number that exceeds about 2^53 the trailing digits will be nonsense, but they should now be _consistent, cross-platform nonsense_.
