### ISSUE TITLE
Segmentation fault on 'mag' AOC 2017 Day 7

### ISSUE THREAD

**Issue by razetime** [JohnEarnest/Decker#41]
**EDIT** minimal repro is `mag 251-243`. the problem was using `mag` on an atom. I read it could be used as absolute value, so i was using it here.

Implementation is C decker. JS decker works fine.

This is a WIP solution for day 7 part2 available [here](https://adventofcode.com/2017/day/7#part2), the program is as follows, and the input is available at [this link](https://github.com/razetime/aoc/blob/main/17/inp/07t). The segfault seems to happen right after `u` is computed.
```
on uniq x do extract first value by value from x end

i:"%s (%i) -> %s" parse -1 drop "\n" split read["inp/07t"]
p:() dict ()
v:() dict ()
p2n:() dict ()
each x in i
  vk:x[0] vv:x[1]
  pv: if x[2] ", " split x[2] else () end
  v[vk]:vv
  each y in pv
    p[y]:vk
  end
  p2n[vk]:pv
end
p1:extract key where !p@key from v
show[p1]
show[p2n]
on p2 d do

  if (count p2n[d])>0
    vals:p2n[d]
    nxt:v@vals
    sums:each x in vals
      a:p2[x]
      show[x,a]
      a
    end
    # show[d,p2n[d]]
    # show["nxt",nxt]
    # show[sums]
    bal:sums

    u:extract list index by value from bal
    u:extract value orderby each x in u count x end asc from u
    show[u]
    if 2=count u
      sms:bal@each x in u first x end
      diff:mag sms[0]-sms[1]
      show[nxt[first first u]-diff]
    end    
    v[d]+sum bal 
  else
    v[d]
  end
end
 
p2[p1]

```

**Comment by JohnEarnest** [comment]
Simple fix; I wasn't being careful enough with my typecasts.

Thanks for the report, and sorry this bit you on an AoC problem. I know firsthand how frustrating it can be to discover a bug in my tools when I'm working on a different time-sensitive problem.

**Comment by razetime** [comment]
Thanks. Luckily this was just practice for AOC. Lil has been serving me surprisingly well for the problems, only hitch i had was with xor operations (then I realized I could just shell out)

**Comment by JohnEarnest** [comment]
That's good to hear!

Maybe there's a logical place for bulk bitwise operations in the `Array` interface; I'll mull it over.
