### ISSUE TITLE
[Clil] '%' behaves strangely on large numbers

### ISSUE THREAD

**Issue by razetime** [JohnEarnest/Decker#42]
Using `%` on large numbers provides incorrect results. I also tried the operation without vectorization and got the same results.
```
  a:1092455,430625591
(1092455,430625591)
  m:16807,48271
(16807,48271)
  a*m
(18360891185,20786727903161)
  mod:2147483647
2147483647
  mod%a*m
(2147483646,2147483646)
```
Seems to be returning a power of two every single time. 
```
  5%a*m
(2,2)
  6%a*m
(4,4)
```
the problem seems to pop up in this range:
```
  5%1000000000
0
  5%10000000000
2
```
The correct answers come up on JSlil:
```
 mod%a*m
(1181022009,1233683848)
 5%a*m
(0,1)
 6%a*m
(5,5)
```
For reference, this problem arose on on [AOC 2017 Day 15](https://adventofcode.com/2017/day/15).

**Comment by JohnEarnest** [comment]
This tweak resolves the immediate problem. There's no reason operands for `%` should be truncated to the range of a c `int`; honestly don't know what I was thinking there.

**Comment by razetime** [comment]
> This tweak resolves the immediate problem
should this issue stay open? I don't see any other problems in my build

**Comment by JohnEarnest** [comment]
I think we can consider this resolved.
