### ISSUE TITLE
More than 50% CPU on Linux native

### ISSUE THREAD

**Issue by santiagogil** [JohnEarnest/Decker#45]
I'm in Ubuntu 22.04, tried compiling with the optimization you sugested on the itch.io forum and with the appimage.

Thanks for this amazing software and the time to read this. :)

**Comment by JohnEarnest** [comment]
I'm glad you're enjoying Decker.

I've made a few enhancements recently that together may speed up native Decker by about 30% while idle; you can try them now or wait for the v1.6 release in the near future.

There's always room for better performance. "Decker uses X% CPU on my computer" or the implied "I would like Decker to be faster" is neither a bug report nor an actionable feature request.

Closing as non-actionable.
