### ISSUE TITLE
[Clil] segfault on (incorrect?) parse

### ISSUE THREAD

**Issue by TeddyDD** [JohnEarnest/Decker#46]
```
"%2a" parse 97
```
results in segfault: `fish: Job 1, 'decker' terminated by signal SIGSEGV (Address boundary error)`.

Decker v1.5, Void Linux 6.0.10_1 x86_64

**Comment by JohnEarnest** [comment]
Should be fixed. Doesn't appear to be a symmetric mistake in the JS implementation.

**Comment by TeddyDD** [comment]
It seems to be fixed, thanks.

**Comment by JohnEarnest** [comment]
Thanks for the report!
