### ISSUE TITLE
Saving (locally?) is broken

### ISSUE THREAD

**Issue by necrophcodr** [JohnEarnest/Decker#48]
When saving a deck as an HTML file via the web-decker system, it doesn't open properly again. The screen is left blank, and it appears to throw errors in the console as follows:

```
Uncaught TypeError: q(...) is null
```

Reproduction is relatively straight forward:
1. Go to https://beyondloom.com/decker/tour.html
2. Save deck as HTML
3. Open locally saved HTML deck
4. Save deck as HTML again
5. Open newly saved HTML deck

I'm not certain why this happens, but it appears that it is NOT the intention for this to happen.

**Comment by necrophcodr** [comment]
Some additional information regarding the platform it was tested on:
Browser: Firefox 107.0.1
OS: NixOS 22.05 64bit

**Comment by JohnEarnest** [comment]
I believe I have identified and corrected this issue.

**Comment by necrophcodr** [comment]
> I believe I have identified and corrected this issue.

Indeed! I've tested the commit before that and that commit as well, and your fix resolves the issue entirely for me. Thank you so much for putting time into this wonderful project!

**Comment by JohnEarnest** [comment]
Thanks for the bug report!
