### ISSUE TITLE
[CDecker, CLil] build error: _POSIX_C_SOURCE: No such file or directory 

### ISSUE THREAD

**Issue by razetime** [JohnEarnest/Decker#49]
Same error occurs on both decker and lilt:
```bash
razetime@razetime-Legion:~/Software$ cd Decker
razetime@razetime-Legion:~/Software/Decker$ make decker
gcc: error: _POSIX_C_SOURCE: No such file or directory
make: *** [Makefile:35: decker] Error 1
razetime@razetime-Legion:~/Software/Decker$ make lilt
gcc: error: _POSIX_C_SOURCE: No such file or directory
make: *** [Makefile:31: lilt] Error 1
```
**OS:** Ubuntu 20.04.5 LTS x86_64

**Comment by JohnEarnest** [comment]
@razetime oops, made a typo.

Line 19 of Makefile should have a `-D` before `_POSIX_C_SOURCE`

**Comment by razetime** [comment]
Cool, that works. The output of the build after changing the makefile:

$ make decker
***@***.***:~/Software/Decker$ make lilt
In file included from ./c/lilt.c:10:
./c/lib/bestline.c:135: warning: "_POSIX_C_SOURCE" redefined
   135 | #define _POSIX_C_SOURCE  1 /* so GCC builds in ANSI mode */
       |
In file included from 
/usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                  from /usr/include/stdlib.h:25,
                  from ./c/lil.h:3,
                  from ./c/lilt.c:2:
/usr/include/features.h:281: note: this is the location of the previous 
definition
   281 | # define _POSIX_C_SOURCE 200809L
       |
In file included from ./c/lilt.c:10:
./c/lib/bestline.c: In function ‘GetLineChar’:
./c/lib/bestline.c:1610:17: warning: ignoring return value of ‘write’, 
declared with attribute warn_unused_result [-Wunused-result]
  1610 |                 write(fout, "\n", 1);
       |                 ^~~~~~~~~~~~~~~~~~~~
./c/lilt.c: In function ‘n_readwav’:
./c/lilt.c:26:66: warning: ignoring return value of ‘fread’, declared 
with attribute warn_unused_result [-Wunused-result]
    26 | 
char*data=calloc(size=st.st_size,1);FILE*f=fopen(name->sv,"rb");fread(data,1,st.st_size,f),fclose(f);

**Comment by JohnEarnest** [comment]
Ugh, every version of GCC complains about something different. Please try the following:

- comment out `#define _POSIX_C_SOURCE  1 /* so GCC builds in ANSI mode */` from `c/lib/bestline.c`.
- add `(void)` to the beginning of line 1610 to explicitly ignore the return value of `write()`.
- replace the `fread()` statement in lilt.c with:
```
if(fread(data,1,st.st_size,f)!=(unsigned)st.st_size)return fclose(f),free(data),sound_make(lms(0));
```

**Comment by JohnEarnest** [comment]
Is this resolved?
