### ISSUE TITLE
Fit into vertical screens

### ISSUE THREAD

**Issue by librarianmage** [JohnEarnest/Decker#51]
Hi!

It would be nice if the UI took up more space when on a vertical (mobile) screen

![6A59D5E4-C795-4356-AC5A-3737FBDA1B36](https://user-images.githubusercontent.com/12386291/211177792-74de96ee-1b48-4b0a-ba86-1b1f7dc7bc9a.png)

**Comment by JohnEarnest** [comment]
Decker is designed for landscape aspect ratios. You may get better results, though, if you check "Decker -> Fullscreen" in web-decker. This will cause most browsers to hide their UI and stretch Decker to fill the available space.

For example, here's how Decker looks on a Fire 8 tablet in fullscreen mode:

![image](https://user-images.githubusercontent.com/400682/211177903-653560f7-31e1-4497-974a-e977509b01f5.png)

**Comment by librarianmage** [comment]
That doesn’t seem to do anything on iOS :(

**Comment by JohnEarnest** [comment]
Did some research and a few experiments, and apparently the phone version of Safari for iOS has no support for fullscreen APIs. May work on an iPad, but I can't really do anything for iPhones.
