### ISSUE TITLE
Selecting "Cancel" in Resources dialog triggers a Seg fault with no error (Mac)

### ISSUE THREAD

**Issue by vga-256** [JohnEarnest/Decker#52]
I noticed that if I select File -> Resources, browse around for a folder without usable resources (e.g. no .html or .deck files or folders available, so the Open button is greyed out), if I click Cancel to exit the dialog, the program crashes with Segmentation Fault: 11. No error report is generated.

Running MacOS 10.14.6

Steps to replicate:

1. File -> Resources... -> Choose
2. Browse to a folder without any sub-folders so that the Open button is greyed out.
3. Click cancel. Program crashes. No error report or error trap.
(if program is run from the Terminal on MacOS, it yields: Segmentation Fault: 11)

![Screen Shot 2023-02-06 at 10 40 33 AM](https://user-images.githubusercontent.com/6203391/217045208-d4497897-bd55-4528-a143-abb3e0824e21.png)

**Comment by JohnEarnest** [comment]
Thanks for the report; should be fixed in the above commit.

**Comment by vga-256** [comment]
Great, thanks so much John. Will test it out.
