### ISSUE TITLE
Guided tour has two fields that are too short, cutting off the bottom pixel

### ISSUE THREAD

**Issue by Xkeeper0** [JohnEarnest/Decker#54]
Basically what it says; the guided tour has a few fields that are a pixel too short, cutting off the descenders for letters like "g":

* canvases: the lil logo loses a pixel of the "p"
* contraption: top left "games" misses the bottom (looks like q)

edit: tested this in web decker and windows native, same result

![image](https://user-images.githubusercontent.com/1077535/232358272-1330a3c7-7490-4d49-95bf-51c12196de60.png)

**Comment by JohnEarnest** [comment]
Easy fix. Thanks for the report.
