### ISSUE TITLE
Feature suggestion: "Card > Go Back" menu item / option in Actions

### ISSUE THREAD

**Issue by Xkeeper0** [JohnEarnest/Decker#55]
The documentation mentions that the `go[]` function takes several keywords; `Next`, `Prev`, `First`, and `Last` all have corresponding `Card` menu / `Action` items, but `Back` is the only one that _only_ works in scripting and isn't available as a menu item/choice.

**Comment by JohnEarnest** [comment]
I believe the above satisfies the request.
Along the way I discovered and corrected a rather nasty bug related to the recently-added transition preview feature.

**Comment by Xkeeper0** [comment]
Does that also impact the Card menu? I'm not well-versed in Decker's code but that commit seems to add it to the Actions dialog box only, not the Card application menu. (I might be wrong, though)

**Comment by JohnEarnest** [comment]
Ah, I missed that aspect of the request. Easy enough to add.
