### ISSUE TITLE
"Text" menu not working

### ISSUE THREAD

**Issue by Xkeeper0** [JohnEarnest/Decker#56]
Decker Native-windows 1.16 / web 1.17

The "Text" menu never enables, making rich text entry difficult/impossible.

Steps to reproduce:

1. Create a new Deck
2. Create a new Field
3. Double click it, ensure it is set to "Rich Text"
4. Focus on the text field. The menu bar shows `Text`, but it is disabled
5. Write text, select text, etc.; Text menu remains disabled
6. ???

I'm not entirely unconvinced there's some other method you're supposed to use, but given that the menu appears but does not ever seem to activate...

![chrome_20230420-185224](https://user-images.githubusercontent.com/1077535/233523544-31a41db3-92e0-47ed-98e8-27d236a8d798.gif)

**Comment by JohnEarnest** [comment]
This is an intentional limitation.

To manipulate rich text in a field, switch to "Interact" mode and focus the field.

See also: https://itch.io/t/2686692/how-can-i-add-rich-text-to-a-field

**Comment by JohnEarnest** [comment]
Making the Text menu and its attendant modals (Link, Fonts) work in every context a rich text field can appear is somewhat easier said than done, but I think the above patch will work.
