### ISSUE TITLE
Changes needed to Makefile and scripts for OpenBSD

### ISSUE THREAD

**Issue by alexshendi** [JohnEarnest/Decker#57]
1. The scripts in scripts/*.sh: Change first line from "#!/bin/bash" to "#!/usr/bin/env bash".
2. Add the following section to Makefile (e.g. after line 4):
````
ifeq ($(UNAME),OpenBSD)
	OPEN=xdg-open
	COMPILER=clang
	FLAGS=-Wall -Werror -Wextra -Wpedantic -O2
	# -Wno-misleading-indentation silences warnings which are entirely spurious.
	FLAGS:=$(FLAGS) -Wno-misleading-indentation -Wno-unknown-warning-option
	FLAGS:=$(FLAGS) -lm
	# FLAGS:=$(FLAGS) -fsanitize=undefined
	# FLAGS:=$(FLAGS) -fsanitize=address
endif
````

Packages needed:
* gmake
* sdl2
* sdl2-image
* vim (for xxd)

I only tried "native" decker.

**Comment by JohnEarnest** [comment]
Seems straightforward. How's that?

**Comment by alexshendi** [comment]
Well it worked for me (on OpenBSD 7.3 on amd64 and i386). I can't imagine the change 
hurts Linux and Darwin. 





Am 19. Mai 2023 18:59:37 MESZ schrieb John Earnest ***@***.***>:
>Seems straightforward. How's that?
>

**Comment by TsukiGva2** [comment]
aditionally, i had to include <sys/wait.h> in c/dom.h, currently there is the following condition:
    
    ...
    #ifdef __NetBSD__
    #include <sys/wait.h>
    #endif
    lv*n_shell(lv*self,lv*a){
            (void)self;lv*x=ls(l_first(a)),*r=lmd();FILE*child=popen(x->sv,"r");str o=str_new();
            while(1){int c=fgetc(child);if(feof(child))break;str_addraw(&o,c);}int e=pclose(child);lv*os=lmstr(o);
            return dset(r,lmistr("out"),lmutf8(os->sv)),dset(r,lmistr("exit"),lmn(WIFEXITED(e)?WEXITSTATUS(e): -1)),r;
    }
    ...

but i had to include it in OpenBSD too.
