### ISSUE TITLE
Weird issue with importing CSV files in Native-Decker

### ISSUE THREAD

**Issue by micpp42** [JohnEarnest/Decker#61]
Hi,
I've enclosed a CSV file that causes some odd behaviour when imported in native Decker

[testbug.csv](https://github.com/JohnEarnest/Decker/files/12168824/testbug.csv)

When I load this into a grid (e.g. using `grid1.value:readcsv[read["text"]]` in the listener) the final character in the bottom-right cell becomes a 1. Even though there is no such 1 there in the original CSV (since the final line is all empty cells)

If I add a newline at the end of the CSV, this does not occur. And I don't get this behaviour in web-decker, just native-decker.

I am guessing there is some sort of weird edge case that causes this?

**Comment by JohnEarnest** [comment]
Should be fixed. Thanks for the report, @micpp42!

**Comment by micpp42** [comment]
Tested in the new version and all good now. Thanks for fixing :)
