### ISSUE TITLE
Translate function on images behaving differently between C and Javascript versions (and I think the JS one is incorrect)

### ISSUE THREAD

**Issue by micpp42** [JohnEarnest/Decker#62]
When I've got an image and I call `x.translate[]` on it passing in non-integer values e.g. `x.translate[(1.5,2)]` the native version of Decker still does the translation, rounding the decimal values to the nearest integer. But the web version blanks out the image when this happens. I'm guessing the behaviour in the native version is probably what should be correct?

Have tested in current versions of both Firefox and Chromium.

**Comment by JohnEarnest** [comment]
You're correct; the intended behavior is an implicit `floor` of the offset pair, as there isn't really a sensible way to perform sub-pixel translation. Thanks for the report!
