### ISSUE TITLE
Installing on Linux

### ISSUE THREAD

**Issue by 1jss** [JohnEarnest/Decker#7]
Huge thanks for this awesome project! Such a creative playground!

I just set it up on Debian and noticed that the install script (`install.sh`) installed lilt, but not decker as stated in the readme. No problems copying it by hand, though. I also crafted a tiny `.desktop` file for myself. Is that something you would like to include in the repo or do you rather keep the packaging outside of the repo?

**Comment by JohnEarnest** [comment]
I'd rather keep packaging outside the repo, but I would accept a PR to tweak the install script to stage the decker binary as well as lilt if it's been compiled; that was an oversight.

**Comment by 1jss** [comment]
Perfect! I'll write a guide for installing on Linux with the added `.desktop` file in a [separate repo](https://github.com/1jss/decker-linux).
