### ISSUE TITLE
Doc says to use canvas.tri[], but should be canvas.poly[]

### ISSUE THREAD

**Issue by treshenry** [JohnEarnest/Decker#72]
I did a copy/paste from the doc on the pinwheel animation and couldn't get it to work for the life of me. I checked the same example in the tour deck (the detail card for canvas) and finally noticed the error. It doesn't look like the canvas interface has a [tri](https://beyondloom.com/decker/decker.html#canvasinterface), so maybe that was a change in the interface and the example in the doc just didn't get updated? I didn't go check. Anyway, PR incoming (for convenience).

**Comment by treshenry** [comment]
As a side note: the lack of any kind of error message in this case was... surprising. Maybe there's some way to check for correctness I'm just not aware of, or some logging somewhere that would have revealed that tri[] isn't defined.

**Comment by JohnEarnest** [comment]
Regarding error messages, accessing an index of an Interface like `canvas.tri` which is invalid is defined to return `0`, so `canvas.tri[]` is equivalent to `(0)[]`.

Calling a function in Lil is identical to indexing into data; both use bracket subscripting syntax (`[]`). Attempting to index into a number is defined to return `0`.

Thus, the entire expression is well-formed and error-free, it simply doesn't do anything useful.

**Comment by treshenry** [comment]
Fair enough, however, while accessing an invalid/undefined index on an interface is designed to return 0, and it's valid in the language design to index into the number 0, I would argue that it's highly unlikely that the user intended to do either, and a message indicating "you probably didn't intend to do this" would be rad (and imo in keeping with the fun and welcoming nature of Decker).

Anyway, I love Decker either way and huge kudos for making this. You sir, are a champion.
