### ISSUE TITLE
Sharp canvas pixels for the web

### ISSUE THREAD

**Issue by treshenry** [JohnEarnest/Decker#75]
Super apologies in advance if this has already been discussed elsewhere! Feel free to close with supreme prejudice.

Depending on the browser, canvas defaults to some sort of smoothing algorithm. For example, in the case of Arc (which is Chromium under the hood), Decker looks like this by default:

<img width="452" alt="decker-smooth" src="https://github.com/JohnEarnest/Decker/assets/35269/58a4a6d9-0d6b-4535-9271-4dea1cc675b0">

Which... ew. However, there is a broadly supported CSS attribute for canvas which can be used to enforce aliasing: [image-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering). Setting this to `pixelated` results in this:

<img width="467" alt="decker-crisp" src="https://github.com/JohnEarnest/Decker/assets/35269/d5745d31-6aff-4209-97c9-b9d982178226">

🧑‍🍳😘

I created an Arc Boost that just sets `image-rendering: pixelated` on all canvas elements on `beyondloom.com/decker` ([available here](https://arc.net/boost/1B8A4B90-447F-4460-947F-7987F880A31D)) for my own use (or for anyone using web-based Decker with Arc) but I think it's maybe worth adding `canvas{image-rendering:pixelated;}` to https://github.com/JohnEarnest/Decker/blob/main/js/decker.html#L10 .

**Comment by JohnEarnest** [comment]
I experimented with this property, but ultimately removed it because the results were frequently _terrible_ on non-Chromium browsers. The behavior is simply too inconsistent to have as a default: https://github.com/JohnEarnest/Decker/commit/d873e2f4ee13b537bf3b7413429b1ff891724de1

**Comment by treshenry** [comment]
Ah 💩. That's unfortunate but also not surprising. I tried Safari, FF, and Chrome (obvs) on my M1 before filing this ticket and they looked good, but I didn't try on any other OS. Weirdly Safari had almost no difference with or without image-rendering:pixelated. Ah well, I'll just stick with my Boost when using the web version.

**Comment by treshenry** [comment]
Closing as invalid.

**Comment by treshenry** [comment]
Closing as invalid.

**Comment by easrng** [comment]
> I experimented with this property, but ultimately removed it because the results were frequently _terrible_ on non-Chromium browsers. The behavior is simply too inconsistent to have as a default: [d873e2f](https://github.com/JohnEarnest/Decker/commit/d873e2f4ee13b537bf3b7413429b1ff891724de1)

Were you making sure canvas pixels were scaled to an integer number of screen pixels?

**Comment by easrng** [comment]
cc @JohnEarnest
