### ISSUE TITLE
Compilation issues on MacOS Ventura

### ISSUE THREAD

**Issue by acmiyaguchi** [JohnEarnest/Decker#76]
I'm having issues compiling decker on my Macbook (m1, ventura) using both the built-in compile (clang 14) and with the latest clang on homebrew.
I see compilation errors of the following form:

```bash
 % make decker
In file included from ./c/decker.c:2:
./c/lil.h:45:12: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   45 | str str_new(){return(str){0,32,calloc(32,1)};}
      |            ^
      |             void
./c/lil.h:81:13: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   81 | void lv_grow(){
      |             ^
      |              void
```

There's a large number of these function declaration without prototype errors.
The web-decker build seems to be fine.

```bash
% clang --version
Homebrew clang version 17.0.6
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

**Comment by JohnEarnest** [comment]
It seems newer versions of `clang` opt into `-Wstrict-prototypes`, which requires functions of no arguments to be declared as `void foo(void)` instead of `void foo()`. C is truly a hideous language.

`web-decker` is not written in C, nor is it compiled, so it is unaffected.

**Comment by acmiyaguchi** [comment]
Aha, that's how you parse the compiler message. Looks like your recent commit fixes the problems I was running into, thanks!

I'm still browsing the codebase, so it's interesting to hear that web-decker is divorced from the compiled applications. I really enjoy the concept and execution, looking forward to poking around. Happy holidays!

**Comment by JohnEarnest** [comment]
I've written a bit about why Decker has two parallel implementations here: http://beyondloom.com/blog/responses.html#whyaretheretwoimplementationsofdecker
