### ISSUE TITLE
feature request: modified click to edit widgets

### ISSUE THREAD

**Issue by tangentstorm** [JohnEarnest/Decker#80]
When authoring a card, I am constantly tripped up by having to switch between interact and widget modes.

It would be really nice if I could do some kind of modified click (ctrl-click or right click or whatever) on a widget to immediately edit that widget's script.

**Comment by tangentstorm** [comment]
alternatively, give us a lil word on the app interface that lets us invoke the editor or switch modes?

**Comment by JohnEarnest** [comment]
I don't like the idea of heavily intermixing interaction and editing; it might be _mildly_ expedient while creating decks, but become a footgun when trying to _use_ an application and e.g. copying and pasting.

The existing "fast path" is using xray mode in the script editor to switch to the script of some particular widget. Starting in interact mode, holding ctrl, and pressing `e` (edit card script), `r` (xray on), and clicking the widget of interest:

![xnav](https://github.com/JohnEarnest/Decker/assets/400682/11163639-ceb1-4ae3-b568-5d42c9922ecc)

In both cards and contraptions it's often convenient to put any complex bits of logic in the "card-level" script (which can be immediately edited via shortcut), allowing events from some or all widgets to bubble up to it, and making individual widgets contain comparatively simple logic.

**Comment by tangentstorm** [comment]
That's interesting. I don't think of what I'm doing as making an application... Rather, decker is the application I'm using to interactively explore some piece of data.

But as for this request, between x-rays and tools I can make myself, I think I can probably smooth this out. Request withdrawn.
