### ISSUE TITLE
bug: current line in transparent grid is unreadable

### ISSUE THREAD

**Issue by tangentstorm** [JohnEarnest/Decker#81]
I thought I'd try putting a background color on my grid, but the current line becomes unreadable when I make it transparent:

![image](https://github.com/JohnEarnest/Decker/assets/2150613/2b3165da-fb1f-4356-8b81-fa77c0e64db7)

**Comment by JohnEarnest** [comment]
![gridbg](https://github.com/JohnEarnest/Decker/assets/400682/1399698b-951d-4c29-9a7e-b11a34350f14)

**Comment by tangentstorm** [comment]
thanks!
