### ISSUE TITLE
tap to click doesn't show menus

### ISSUE THREAD

**Issue by easrng** [JohnEarnest/Decker#83]
Maybe instead checking how long the mouse is down you should measure how much the mouse moves instead?
I'm using KDE on NixOS

**Comment by JohnEarnest** [comment]
I haven't been able to reproduce this. Is this a Firefox-specific issue?

**Comment by easrng** [comment]
It happens for me on both firefox and chromium

**Comment by JohnEarnest** [comment]
I'm going to hazard that https://github.com/JohnEarnest/Decker/pull/102 addresses this issue. Feel free to reopen with additional clarification if this is not the case.
