### ISSUE TITLE
configurable home/end behavior

### ISSUE THREAD

**Issue by easrng** [JohnEarnest/Decker#85]
I am very used to using home and end to jump to the start and end of a line, with ^ making it file wide. I think this is standard everywhere except mac? It really messes with my muscle memory when I'm typing in decker.

**Comment by JohnEarnest** [comment]
This sounds like it would be the first instance of a configurable, persistent setting for Decker. It's certainly possible, but it's unclear to me where best to track such information, and whether there's a reasonable way to have parity in web-decker with native-decker in this respect.

If this were implemented, perhaps other things could also be preserved:

- Toolbar visible/hidden?
- Grid overlay dimensions?
- Default document path?

**Comment by JohnEarnest** [comment]
After some thought, I've decided to simply change the behavior rather than introduce options.
