### ISSUE TITLE
Desktop Version Collision Problems: Draggable functions working improperly

### ISSUE THREAD

**Issue by thisLewashi** [JohnEarnest/Decker#87]
Lil functions overlaps[] and constrain[] don't work right on the desktop version.
I've downloaded Decker 1.41 for Desktop from itch.io on my Windows 10 PC and have noticed that certain draggable code for canvases don't work. For example, the following code from the demo:
```on release do
 if rect.overlaps[me target]
  alert["You hit the target!"]
 end
end
```
doesn't work when the entire card is copied and pasted into the desktop mode; no alert shows and print statements show that a collision is never detected. 
Additionally, constrain[] locks the draggable to the top corner:
![image](https://github.com/JohnEarnest/Decker/assets/76401985/7e4945e9-1634-4e36-b73f-08a3d6575f79)
I believe it may be a problem with the scale detection of the application. Is it just me, or can this be replicated? Thank you for your hard work and this awesome application.

**Comment by JohnEarnest** [comment]
Did you import the `rect` module? Without it, none of those utility methods will be defined.
