### ISSUE TITLE
Official prebuild release

### ISSUE THREAD

**Issue by edwinjhlee** [JohnEarnest/Decker#89]
Hi, friends in Decker community,

I am wondering if decker or lil or any other cool cli tools in this community can be packaged into x-cmd pkg. We hope the official can provide prebuilt binaries in the github release. APE is also acceptable.

---

x-cmd is not well-known by developers. Please let me introduce x-cmd

User can easily use 500+ portable binary with x-cmd pkg. Take jq for example https://x-cmd.com/pkg/jq

We also provide some supports for cosmo ecosystem. https://x-cmd.com/mod/cosmo

**Comment by JohnEarnest** [comment]
I'm not really clear on the nature of your project, but you are welcome to redistribute or package Decker, Lilt, or any other component of this repository provided you comply with the requirements of the MIT license.

Periodic binary releases of Decker and an APE build of Lilt are available on [Itch.io](https://internet-janitor.itch.io/decker).

**Comment by edwinjhlee** [comment]
I found the APE build of lilt in the ltch.io ...

---

x-cmd is a posix shell library. Upon this library, we build x-cmd pkg -- the user can use 500+ tools without sudo priviledge in windows, linux, macos

https://www.x-cmd.com/start/guide
