### ISSUE TITLE
Should Lilt be optional in the installer?

### ISSUE THREAD

**Issue by 1jss** [JohnEarnest/Decker#9]
The installer script halts if Lilt or Decker binaries are not found. Should Lilt be required or should the installer continue, just noting that the Lilt binary was missing?

**Comment by JohnEarnest** [comment]
Probably the latter: lilt and decker are each usable on their own.

If you're planning on making more tweaks to the install script, you might also want to update the uninstall script to reflect the installation of the decker binary.

**Comment by 1jss** [comment]
Good. I'll update the install script and add decker to the uninstall script as well.
