### ISSUE TITLE
Web Decker disallows multiple legit identifiers

### ISSUE THREAD

**Issue by JaSpa** [JohnEarnest/Decker#99]
There are some identifiers which result in an error when used as variable names in Web Decker, e.g. `constructor`, `valueOf`, `toString`, `__proto__` and others.

Culprit are the `n in …` checks in the `ident` function in the JS code.

https://github.com/JohnEarnest/Decker/blob/41f95e96557fc230c00c9150aecb339c452d2b6e/js/lil.js#L494-L495

The JS `in` operator does not only check for the object's properties but also properties inherited from the prototype chain. ([Docs][in-operator]) The identifiers listed at the top come from `Object.prototype`, more are [listed here][prototype-ops].

A solid replacement for the `in` operator with very decent browser support is [`Object.prototype.hasOwnProperty()`][Object-hop] which does the thing you'd expect `in` to do.

At a first glance there seem to be quite a few places besides the `ident` function where the `in` operator appears. I think it is a good idea to replace all of those with a call to `hasOwnProperty()`. (Obviously, except for places where `in`'s behaviour is actually wanted.) If you want I can prepare a patch sometime this week.

[Object-hop]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty
[in-operator]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in
[prototype-ops]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object#object_prototype_properties

**Comment by JohnEarnest** [comment]
I'll handle this.
